// Reads the sprite-sheet PNGs and inlines them as base64 data URIs into a generated
// TS module. Inlining means no web_accessible_resources entry, CSP-safe, offline.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const SPRITE_DIR = join(here, '..', 'src', 'assets', 'sprites')
const OUT = join(here, '..', 'src', 'shared', 'sprites.generated.ts')

const ANIMALS = ['cat', 'dog', 'bunny']

const entries = []
for (const a of ANIMALS) {
  const p = join(SPRITE_DIR, `${a}.png`)
  if (!existsSync(p)) {
    console.error(`pack-sprites: missing ${a}.png in src/assets/sprites/`)
    process.exit(1)
  }
  const b64 = readFileSync(p).toString('base64')
  entries.push(`  ${a}: 'data:image/png;base64,${b64}',`)
}

const content = `// AUTO-GENERATED by scripts/pack-sprites.mjs — do not edit by hand.
// Sprite sheets inlined as base64 data URIs: no remote code, no web_accessible_resources, offline + CSP-safe.
import type { Animal } from './types'

export const SHEETS: Record<Animal, string> = {
${entries.join('\n')}
}
`

writeFileSync(OUT, content)
console.log(`wrote sprites.generated.ts (${entries.length} sheets)`)
